[package]
name = "hyperion-crafting"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[dependencies]
valence_protocol.workspace = true

bevy_ecs.workspace = true

anyhow.workspace = true
slotmap.workspace = true

[lints]
workspace = true
