[package]
name = "hyperion-command"
version.workspace = true
edition.workspace = true
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
hyperion.workspace = true
hyperion-utils.workspace = true
indexmap.workspace = true
itertools.workspace = true
tracing.workspace = true
valence_bytes.workspace = true

[lints]
workspace = true
