[package]
name = "hyperion-proto"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[dependencies]
rkyv.workspace = true
glam.workspace = true

[lints]
workspace = true
