[package]
name = "simd-utils"
version.workspace = true
edition.workspace = true
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]

[dev-dependencies]
proptest.workspace = true
aligned-vec.workspace = true

[lints]
workspace = true
