[package]
name = "hyperion-genmap"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[dependencies]
hyperion.workspace = true
hyperion-utils.workspace = true

bevy_app.workspace = true

[lints]
workspace = true
