[package]
name = "hyperion-palette"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[dependencies]
valence_protocol.workspace = true

anyhow.workspace = true
roaring.workspace = true

[lints]
workspace = true
